### Customer Requests
POST http://localhost:3001/API/Customer/FetchAvailableTable
### Working Sample POST Request
POST http://localhost:3001/API/Customer/NewSession
content-type: application/json

{
    "Name": "Jireh Lozana",
    "Address": "Candau-ay",
    "Phone": "0921233121",
    "Table": "4",
    "Checkout": [
        {"food": "Barnuts", "qty": 25,"price": 5, "total": 125},
        {"food": "Chicken", "qty": 25,"price": 5, "total": 125},
        {"food": "Burger", "qty": 25,"price": 5, "total": 125},
        {"food": "Nuts", "qty": 25,"price": 5, "total": 125},
        {"food": "Deez", "qty": 25,"price": 5, "total": 125}  
    ]
}