### Customer Requests
POST http://localhost:3001/API/Customer/FetchAvailableTable
###
POST http://localhost:3001/API/Customer/FetchMenuData
###
POST http://localhost:3001/API/Customer/PushLogInformation
content-type: application/json
{
    # Body info here
}
###
POST http://localhost:3001/API/Customer/PushOrderSessionInformation
content-type: application/json
{
    # Body info here
}