### Authentication endpoit
POST http://localhost:3001/API/Admin/Authenticate
content-type: application/json

{
    "Username": "admin",
    "Password": "admin"
}
### Registration endpoint
POST http://localhost:3001/API/Admin/Register
content-type: application/json

{
    "Username": "admin",
    "Password": "admin",
    "Fullname": "Sean Christian Lozana",
    "Contact": "09455477432",
    "Address": "Candau-ay, Dumaguete City"
}

### Jwt Test Endpoint
POST http://localhost:3001/API/Admin/Authenticate
content-type: application/json

{
    "Username": "admin",
    "Password": "admin"
}

### Protected API Endpoint Test
POST http://localhost:3001/API/Admin/GetSales
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImFkbWluIiwiUGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYxNTc3MDcyNX0.tHAfPRahmyAB32Z98XM4GUIEdu23gUepzN6zimwLbFs